---
- hosts: all
  gather_facts: no
  tasks:
    - name: Check systemd minio status
      command: systemctl status minio
      register: minio_status
      failed_when: not (minio_status.stdout_lines | select("match", "4 Online, 0 Offline."))

- hosts: localhost
  tasks:
    - name: Check prometheus status [from the host]
      uri:
        url: "http://127.0.0.1:{{ item }}/minio/prometheus/metrics"
        status_code: 200
      with_items:
        - 9000
        - 9001
        - 9002
        - 9003

