---
- hosts: all
  roles:
    - name: atosatto.minio
      vars:
        minio_access_key: "foo"
        minio_secret_key: "barbarbar"
        minio_server_addr: "0.0.0.0:9000"
        minio_server_env_extra: "MINIO_PROMETHEUS_AUTH_TYPE=public"
        minio_server_datadirs:
          - /minio-data
        minio_server_cluster_nodes:
          - http://minio{0...3}/minio-data
